#!/usr/bin/env bash

source scripts/install_brew.sh
source scripts/install_wget.sh
source scripts/install_iterm2.sh
source scripts/install_oh_my_zsh.sh
source scripts/install_visual_studio_code.sh
source scripts/install_sublime_text.sh
source scripts/install_jetbrains_toolbox.sh
source scripts/install_tableplus.sh
source scripts/create_dev_directory.sh
source scripts/install_laravel_installer.sh
source scripts/install_redis.sh
source scripts/install_postman.sh
source scripts/install_npm.sh
source scripts/install_yarn.sh
source scripts/install_snazzy.sh
source scripts/install_pure_prompt.sh
source scripts/install_slack.sh
source scripts/install_rocket_chat.sh
source scripts/install_rescuetime.sh
source scripts/install_toptracker.sh
source scripts/install_raycast.sh
source scripts/install_dropbox.sh
source scripts/install_1password.sh
source scripts/install_bitwarden.sh
source scripts/install_google_chrome.sh
source scripts/install_drawio.sh
source scripts/install_imageoptim.sh

function install_mmacenv() {
  create_dev_directory
  install_brew
  install_wget
  install_iterm2
  install_oh_my_zsh
  install_atom
  install_sublime_text
  install_visual_studio_code
  install_jetbrains_toolbox
  install_tableplus
  install_laravel_installer
  install_redis
  install_postman
  install_npm
  install_yarn
  install_snazzy
  install_pure_prompt
  install_slack
  install_rocket_chat
  install_rescuetime
  install_toptracker
  install_raycast
  install_dropbox
  install_1password
  install_bitwarden
  install_google_chrome
  install_drawio
  install_imageoptim
  install_docker
}

echo ">> You can run one of:"

echo " - create_dev_directory"
echo " - install_brew"
echo " - install_wget"
echo " - install_iterm2"
echo " - install_oh_my_zsh"
echo " - install_sublime_text"
echo " - install_visual_studio_code"
echo " - install_jetbrains_toolbox"
echo " - install_tableplus"
echo " - install_laravel_installer"
echo " - install_redis"
echo " - install_postman"
echo " - install_npm"
echo " - install_yarn"
echo " - install_snazzy"
echo " - install_pure_prompt"
echo " - install_slack"
echo " - install_rocket_chat"
echo " - install_rescuetime"
echo " - install_toptracker"
echo " - install_raycast"
echo " - install_dropbox"
echo " - install_1password"
echo " - install_bitwarden"
echo " - install_google_chrome"
echo " - install_drawio"
echo " - install_docker"

echo " - install_mmacenv (will install all)"
