#!/usr/bin/env bash

source scripts/install_brew.sh
source scripts/install_wget.sh
source scripts/install_iterm2.sh
source scripts/install_oh_my_zsh.sh
source scripts/install_atom.sh
source scripts/install_phpstorm_2016_1_2.sh
source scripts/create_dev_directory.sh
source scripts/install_virtual_box.sh
source scripts/install_vagrant.sh
source scripts/install_npm.sh
source scripts/install_yarn.sh
source scripts/install_snazzy.sh
source scripts/install_pure_prompt.sh
source scripts/install_slack.sh

function install_mmacenv() {
  install_brew
  install_wget
  install_iterm2
  install_oh_my_zsh
  install_atom
  install_phpstorm_2016_1_2
  install_virtual_box
  install_vagrant
  install_npm
  install_yarn
  install_snazzy
  install_pure_prompt
  install_slack
  create_dev_directory
}

echo ">> You can run one of:"
echo " - create_dev_directory"
echo " - install_brew"
echo " - install_wget"
echo " - install_iterm2"
echo " - install_oh_my_zsh"
echo " - install_atom"
echo " - install_phpstorm_2016_1_2"
echo " - install_virtual_box"
echo " - install_vagrant"
echo " - install_npm"
echo " - install_yarn"
echo " - install_snazzy"
echo " - install_pure_prompt"
echo " - install_slack"
echo " - install_mmacenv (will install all)"
